### PR TITLE
Option to disable drag gesture

### PR DESCRIPTION
**Pull request by nedimf**
I have View where I use SwiftUI Picker and this package ```dragging gesture``` overrides default dragging functionality of that element. I added ```disableDragGesture:Bool``` to take care of this, I've tested it briefly, you may want to test it more.

### CODE REVIEW

**Comment by gordan-glavas-codecons** [comment]
I tried reproing this by adding a wheel-style Picker in both the side menu and the main view, but couldn't find any issues - I'm able to scroll both pickers, as well as trigger the opening/closing animation by a horizontal drag anywhere on the screen. Could you please share more info on what you're doing so that I can repro it on my end?

**Comment by nedimf** [comment]
My issue occurred with using ```SwiftUI Segmented Picker``` on top of view, I assumed it was because dragging gesture gets overridden by this module. Did you test this on simulator or just real device, because on simulator I was getting this issue.

**Comment by gordan-glavas-codecons** [comment]
Please check this out and let me know if it's any different than your setup:

https://user-images.githubusercontent.com/6662291/132184584-8a7ab810-81ee-4c2f-a939-fbc721d8e4b6.mov

**Comment by nedimf** [comment]
Seems like issue was with my view hierarchy, so I'll be closing this PR. Thanks for engaging to solve this issue.

**Pull request closed without merging**
